### ISSUE TITLE
(Question) Does it support Markdown files?

### ISSUE THREAD

**Issue by hardBSDk** [emmyoh/vox#1]
Convert Markdown files to HTML, like other static site generators.

**Comment by emmyoh** [comment]
Hello!

The short answer is 'Yes', but it's not that simple.

A `.vox` file has two parts: the frontmatter at the top (written in TOML) that defines the page's data, and the body afterwards.

A Vox page's body is written in [the Liquid templating language](https://shopify.github.io/liquid/); I've implemented a `{% markdown %}` Liquid block.

Here's an example of a Vox page using markdown:

```
---
title = "Example"
permalink = "example.html"
---

{% markdown %}

# {{ page.title }}
## These are headings

Here's some **emphasised text**.

{% endmarkdown %}
```

**Comment by hardBSDk** [comment]
@emmyoh It was implemented this way to satisfy the industry standards?

**Comment by emmyoh** [comment]
It was implemented this way to allow the usage of both Liquid templating and Markdown at the same time without breaking support for writing HTML. Liquid allows you to use variables, perform logical operations, etc, so it's very necessary for Vox to have it. Regarding Markdown, placing it in a Liquid block (as opposed to treating all rendered Liquid as Markdown) helps prevent issues when you're trying to include HTML inside a page (eg, making page layouts, snippets, etc) as Markdown rendering will break HTML markup.
